/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellersRouteImport } from './routes/sellers'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellersSlugRouteImport } from './routes/sellers.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AuthenticatedSellerRouteImport } from './routes/_authenticated/seller'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedSellerIndexRouteImport } from './routes/_authenticated/seller.index'
import { Route as AuthenticatedSellerProductsRouteImport } from './routes/_authenticated/seller.products'
import { Route as AuthenticatedSellerOrdersRouteImport } from './routes/_authenticated/seller.orders'
import { Route as AuthenticatedSellerProductsNewRouteImport } from './routes/_authenticated/seller.products.new'
import { Route as AuthenticatedSellerProductsIdRouteImport } from './routes/_authenticated/seller.products.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersRoute = SellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellersSlugRoute = SellersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SellersRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSellerRoute = AuthenticatedSellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellerIndexRoute =
  AuthenticatedSellerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProductsRoute =
  AuthenticatedSellerProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerOrdersRoute =
  AuthenticatedSellerOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedSellerRoute,
  } as any)
const AuthenticatedSellerProductsNewRoute =
  AuthenticatedSellerProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSellerProductsRoute,
  } as any)
const AuthenticatedSellerProductsIdRoute =
  AuthenticatedSellerProductsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSellerProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/sellers': typeof SellersRouteWithChildren
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/seller': typeof AuthenticatedSellerRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/seller/': typeof AuthenticatedSellerIndexRoute
  '/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/sellers': typeof SellersRouteWithChildren
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/product/$slug': typeof ProductSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/seller': typeof AuthenticatedSellerIndexRoute
  '/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/b2b': typeof B2bRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/sellers': typeof SellersRouteWithChildren
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/seller': typeof AuthenticatedSellerRouteWithChildren
  '/product/$slug': typeof ProductSlugRoute
  '/sellers/$slug': typeof SellersSlugRoute
  '/_authenticated/seller/orders': typeof AuthenticatedSellerOrdersRoute
  '/_authenticated/seller/products': typeof AuthenticatedSellerProductsRouteWithChildren
  '/_authenticated/seller/': typeof AuthenticatedSellerIndexRoute
  '/_authenticated/seller/products/$id': typeof AuthenticatedSellerProductsIdRoute
  '/_authenticated/seller/products/new': typeof AuthenticatedSellerProductsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/b2b'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-confirmed'
    | '/sellers'
    | '/shop'
    | '/signup'
    | '/account'
    | '/seller'
    | '/product/$slug'
    | '/sellers/$slug'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/'
    | '/seller/products/$id'
    | '/seller/products/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/b2b'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-confirmed'
    | '/sellers'
    | '/shop'
    | '/signup'
    | '/account'
    | '/product/$slug'
    | '/sellers/$slug'
    | '/seller/orders'
    | '/seller/products'
    | '/seller'
    | '/seller/products/$id'
    | '/seller/products/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/b2b'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/order-confirmed'
    | '/sellers'
    | '/shop'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/seller'
    | '/product/$slug'
    | '/sellers/$slug'
    | '/_authenticated/seller/orders'
    | '/_authenticated/seller/products'
    | '/_authenticated/seller/'
    | '/_authenticated/seller/products/$id'
    | '/_authenticated/seller/products/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  B2bRoute: typeof B2bRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  SellersRoute: typeof SellersRouteWithChildren
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers': {
      id: '/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof SellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sellers/$slug': {
      id: '/sellers/$slug'
      path: '/$slug'
      fullPath: '/sellers/$slug'
      preLoaderRoute: typeof SellersSlugRouteImport
      parentRoute: typeof SellersRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/seller': {
      id: '/_authenticated/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof AuthenticatedSellerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seller/': {
      id: '/_authenticated/seller/'
      path: '/'
      fullPath: '/seller/'
      preLoaderRoute: typeof AuthenticatedSellerIndexRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/products': {
      id: '/_authenticated/seller/products'
      path: '/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof AuthenticatedSellerProductsRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/orders': {
      id: '/_authenticated/seller/orders'
      path: '/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof AuthenticatedSellerOrdersRouteImport
      parentRoute: typeof AuthenticatedSellerRoute
    }
    '/_authenticated/seller/products/new': {
      id: '/_authenticated/seller/products/new'
      path: '/new'
      fullPath: '/seller/products/new'
      preLoaderRoute: typeof AuthenticatedSellerProductsNewRouteImport
      parentRoute: typeof AuthenticatedSellerProductsRoute
    }
    '/_authenticated/seller/products/$id': {
      id: '/_authenticated/seller/products/$id'
      path: '/$id'
      fullPath: '/seller/products/$id'
      preLoaderRoute: typeof AuthenticatedSellerProductsIdRouteImport
      parentRoute: typeof AuthenticatedSellerProductsRoute
    }
  }
}

interface AuthenticatedSellerProductsRouteChildren {
  AuthenticatedSellerProductsIdRoute: typeof AuthenticatedSellerProductsIdRoute
  AuthenticatedSellerProductsNewRoute: typeof AuthenticatedSellerProductsNewRoute
}

const AuthenticatedSellerProductsRouteChildren: AuthenticatedSellerProductsRouteChildren =
  {
    AuthenticatedSellerProductsIdRoute: AuthenticatedSellerProductsIdRoute,
    AuthenticatedSellerProductsNewRoute: AuthenticatedSellerProductsNewRoute,
  }

const AuthenticatedSellerProductsRouteWithChildren =
  AuthenticatedSellerProductsRoute._addFileChildren(
    AuthenticatedSellerProductsRouteChildren,
  )

interface AuthenticatedSellerRouteChildren {
  AuthenticatedSellerOrdersRoute: typeof AuthenticatedSellerOrdersRoute
  AuthenticatedSellerProductsRoute: typeof AuthenticatedSellerProductsRouteWithChildren
  AuthenticatedSellerIndexRoute: typeof AuthenticatedSellerIndexRoute
}

const AuthenticatedSellerRouteChildren: AuthenticatedSellerRouteChildren = {
  AuthenticatedSellerOrdersRoute: AuthenticatedSellerOrdersRoute,
  AuthenticatedSellerProductsRoute:
    AuthenticatedSellerProductsRouteWithChildren,
  AuthenticatedSellerIndexRoute: AuthenticatedSellerIndexRoute,
}

const AuthenticatedSellerRouteWithChildren =
  AuthenticatedSellerRoute._addFileChildren(AuthenticatedSellerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedSellerRoute: typeof AuthenticatedSellerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedSellerRoute: AuthenticatedSellerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SellersRouteChildren {
  SellersSlugRoute: typeof SellersSlugRoute
}

const SellersRouteChildren: SellersRouteChildren = {
  SellersSlugRoute: SellersSlugRoute,
}

const SellersRouteWithChildren =
  SellersRoute._addFileChildren(SellersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  B2bRoute: B2bRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  SellersRoute: SellersRouteWithChildren,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
